test env var gh action

diff --git a/.github/workflows/gds.yaml b/.github/workflows/gds.yaml
--- a/.github/workflows/gds.yaml
+++ b/.github/workflows/gds.yaml
@@ -56,7 +56,7 @@ jobs:
 
       - name: Fetch verilog and build config
         shell: bash
-        run: ./tt/tt_tool.py --create-user-config $TT_ARGS
+        run: ./tt/tt_tool.py --create-user-config ${{ env.TT_ARGS }}
 
       - name: Install LibreLane
         shell: bash
@@ -81,7 +81,7 @@ jobs:
 
       - name: Make GDS with LibreLane
         shell: bash
-        run: ./tt/tt_tool.py --harden $TT_ARGS
+        run: ./tt/tt_tool.py --harden ${{ env.TT_ARGS }}
 
       - name: Show build files (for debugging)
         shell: bash
@@ -135,15 +135,15 @@ jobs:
 
       - name: Yosys warnings
         shell: bash
-        run: ./tt/tt_tool.py --print-warnings $TT_ARGS >> $GITHUB_STEP_SUMMARY
+        run: ./tt/tt_tool.py --print-warnings ${{ env.TT_ARGS }} >> $GITHUB_STEP_SUMMARY
 
       - name: Routing summary
         shell: bash
-        run: ./tt/tt_tool.py --print-stats $TT_ARGS >> $GITHUB_STEP_SUMMARY
+        run: ./tt/tt_tool.py --print-stats ${{ env.TT_ARGS }} >> $GITHUB_STEP_SUMMARY
 
       - name: Cell usage summary
         shell: bash
-        run: ./tt/tt_tool.py --print-cell-category $TT_ARGS >> $GITHUB_STEP_SUMMARY
+        run: ./tt/tt_tool.py --print-cell-category ${{ env.TT_ARGS }} >> $GITHUB_STEP_SUMMARY
 
       - name: Publish build logs
         if: success() || failure()
@@ -156,7 +156,7 @@ jobs:
 
       - name: Prepare tt_submission artifact
         shell: bash
-        run: ./tt/tt_tool.py --create-tt-submission $TT_ARGS
+        run: ./tt/tt_tool.py --create-tt-submission ${{ env.TT_ARGS }}
 
       - name: Publish tt_submission artifact
         uses: actions/upload-artifact@v4
@@ -171,7 +171,7 @@ jobs:
 
       - name: Render PNG from GDS
         shell: bash
-        run: './tt/tt_tool.py --create-png $TT_ARGS 2>&1 || echo "WARNING: Failed to render PNG preview from GDS; error $?"'
+        run: './tt/tt_tool.py --create-png ${{ env.TT_ARGS }} 2>&1 || echo "WARNING: Failed to render PNG preview from GDS; error $?"'
 
       - name: Upload gds_render (png) artifact
         uses: actions/upload-artifact@v4
